version: "3.9"
services:
  redis:
    image: "redis:latest"
    ports:
      - "127.0.0.1:6379:6379"

  selenium:
    image: "seleniarm/standalone-chromium:latest"
    container_name: "selen"
    ports:
      - "4444"
      - "127.0.0.1:7900:7900"
    shm_size: 2gb
    environment:
      - SE_SCREEN_WIDT=1366
      - SE_SCREEN_HEIGHT=768

  proxy:
    build:
      context: ./browsermob-proxy-2.1.4
    ports:
      - "8080"
      - "8082"

  worker:
    build:
      context: .
    command: sh -c '/bin/wait-for http://selenium:4444/ -- python3 main.py'
    environment:
      - EMAIL=${EMAIL}
      - PASS=${PASS}
      - PROXY_URI=proxy:8080
      - RUCAPTCHA_TOKEN=${RUCAPTCHA_TOKEN}
      - WEBDRIVER=http://selenium:4444
      - RHOST=redis
      - RPORT=6379
    depends_on:
      - redis
      - proxy
      - selenium
