version: "3"
services:
  selenium:
    image: "seleniarm/standalone-chromium:latest"
    ports:
      - "4444"
      - "127.0.0.1:${VNCDEBUG}:7900"
    shm_size: 2gb
    restart: always
    environment:
      - SE_SCREEN_WIDT=1366
      - SE_SCREEN_HEIGHT=768

  proxy:
    build:
      context: ./browsermob-proxy-2.1.4
    restart: always
    ports:
      - "8080"
      - "8082"

  worker:
    build:
      context: .
    command: sh -c '/bin/wait-for http://selenium:4444/ -- python3 main.py'
    restart: always
    environment:
      - EMAIL
      - PASS
      - PROXY_URI=proxy:8080
      - RUCAPTCHA_TOKEN
      - WEBDRIVER=http://selenium:4444
      - RHOST=172.17.0.1
      - RPORT=6379
    depends_on:
      - proxy
      - selenium
